name: Scala CI

on:
  push:
    branches: [ main ]

defaults:
 run:
  working-directory: ./data-engineering/tp-cooperation

jobs:
  run-my-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
      
  run-coverage:
      needs: run-my-tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run clean coverage
        run: sbt clean coverage test
      - name: Run coverageReport
        run: sbt coverageReport
